import { WorkEntry, ExpenseEntry, DriverShift } from './types';

export const HARVESTER_LOGO =
  'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="%2318532c"/><stop offset="100%" stop-color="%23124222"/></linearGradient><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="%23FDE047"/><stop offset="100%" stop-color="%23CA8A04"/></linearGradient></defs><rect width="100" height="100" rx="24" fill="url(%23bg)"/><circle cx="50" cy="50" r="44" stroke="%234ade80" stroke-width="1.5" stroke-opacity="0.25" stroke-dasharray="4 2"/><path d="M32 30 H56 C60 30 63 33 64 37 L67 52 H28 L30 33 C30.5 31.3 31.2 30 32 30 Z" fill="%23FFFFFF"/><path d="M35 34 H54 L52 46 H33 Z" fill="%230F2E1B"/><rect x="22" y="50" width="56" height="15" rx="3" fill="url(%23g)"/><circle cx="80" cy="56" r="12" fill="none" stroke="url(%23g)" stroke-width="3.5"/><circle cx="80" cy="56" r="3.5" fill="%23FFFFFF"/><circle cx="36" cy="68" r="11" fill="%230D2817" stroke="url(%23g)" stroke-width="3"/><circle cx="58" cy="68" r="9" fill="%230D2817" stroke="url(%23g)" stroke-width="3"/><path d="M16 75 Q 14 45 22 24" stroke="url(%23g)" stroke-width="2.5" fill="none" stroke-linecap="round"/><circle cx="75" cy="24" r="10" fill="url(%23g)"/><text x="75" y="28" fill="%23144026" font-size="11" font-weight="bold" font-family="sans-serif" text-anchor="middle">₹</text></svg>';

export const HARVESTER_BANNER_IMG =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuAGBPIzzRT27M1nTuk6sE2k81gzXtGnnah0buJo7_vTtfhZkuVxnPQEmTJmjNkoCpnFtz-OPHMbLHfcJOk7apufVr_aHFxv16VD6rr2pXHfO1_dMjPrkxlN1OdXZsBsIc0zdr43Ar2RRAc0hGOf-QCac9yD3QR2nokCNQMn0swJByaPPQK6emeZVWHlfffzGi5O3XUBcjoKjfHV2MufzgucEIsT8srCJwBLkT7DfkAzWbGYc09HksQ';

export const HARVESTER_PHOTO_SQ =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuDZ4bW-6_U5W7C5KYWkgvR31cgpkuKv51aiXlWbbw1vMdqT3hlwtHDBr5gxLdKCqzxVTvCjYm1fRC_bPormK0RwZTzbTKohJmkpCcfQD_C8oyLsjEof2Q2CveVpqmdjmBqnyGC1OAtES1lne11FTVLtbhPKOYxfPXeqh4LKge-XtM1app4xDTSJGbqTsirqOe3EhwjL9r6qDFA4V5ZsqOaHFyocdRicAGMkUegOFv82uUc6O9LT88I';

export const FUEL_RECEIPT_IMG =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuDWBr7p4FEKdBJ2shpChYTCP0RH1pRleRTwQd1ZoWFkhFScr_fB_7FPuJ5lcA3VomFbeEnlY1kpRYLuIG7xP--JmNZigeDFXEqZCpHqhExTBu4s6BFIR0NvtfxKfHMEZIhk_oa7qFu-EzK5MZEyQWShec97VKQez6Hvi330jaDI6LpiJsfec6IHQoiVbrdr3ftDMKhZsAtqx0kopOMjZ6S9B3wiqgn_ZyeCArvNioxN2dtmCfWNRUg';

export const INITIAL_WORK_ENTRIES: WorkEntry[] = [
  {
    id: 'work-1',
    farmerName: 'Kempegowda (Gowda Farm)',
    village: 'Maddur Village',
    phone: '9842011234',
    crop: 'paddy',
    cropVariety: 'Paddy (IR-64)',
    fieldOwnership: 'customer',
    unit: 'acres',
    quantity: 4.8,
    rate: 3000,
    totalAmount: 14400,
    receivedAmount: 14400,
    balanceAmount: 0,
    status: 'paid',
    date: 'Today, 18 Nov 2024',
    time: '2:30 PM',
    receivedBy: 'anand',
    paymentMode: 'cash',
    driverName: 'Ramesh',
    remarks: 'Field harvested cleanly, cash given on spot by Gowda.',
    receiptNumber: 'HB-2024-121',
    verified: true,
  },
  {
    id: 'work-2',
    farmerName: 'Ramasamy Gounder',
    village: 'Semmipalayam',
    phone: '9842012345',
    crop: 'paddy',
    cropVariety: 'Paddy Cutting',
    fieldOwnership: 'customer',
    unit: 'acres',
    quantity: 4.5,
    rate: 2800,
    totalAmount: 12600,
    receivedAmount: 8000,
    balanceAmount: 4600,
    status: 'partly_paid',
    date: '17 Nov 2024',
    time: '4:15 PM',
    receivedBy: 'anand',
    paymentMode: 'cash',
    driverName: 'Ramesh',
    remarks: 'East side field near canal, will pay balance next Tuesday',
    receiptNumber: 'HB-2024-120',
    verified: true,
  },
  {
    id: 'work-3',
    farmerName: 'S. Manjunatha',
    village: 'Koppa Cross',
    phone: '9842023456',
    crop: 'ragi',
    cropVariety: 'Ragi Dry Field',
    fieldOwnership: 'customer',
    unit: 'acres',
    quantity: 5.2,
    rate: 3500,
    totalAmount: 18200,
    receivedAmount: 10000,
    balanceAmount: 8200,
    status: 'partly_paid',
    date: 'Yesterday, 5:45 PM',
    time: '5:45 PM',
    receivedBy: 'boopathi',
    paymentMode: 'upi',
    driverName: 'Ramesh',
    remarks: 'Boopathi logged. Balance promised after grain sale at mandi.',
    receiptNumber: 'HB-2024-119',
    verified: true,
  },
  {
    id: 'work-4',
    farmerName: 'Marappa Gowda',
    village: 'Kethanur',
    phone: '9842098765',
    crop: 'ragi',
    cropVariety: 'Ragi Harvesting',
    fieldOwnership: 'customer',
    unit: 'hours',
    quantity: 3.0,
    rate: 2200,
    totalAmount: 6600,
    receivedAmount: 0,
    balanceAmount: 6600,
    status: 'pending',
    date: '16 Nov 2024',
    time: '1:00 PM',
    receivedBy: 'boopathi',
    paymentMode: 'cash',
    driverName: 'Ramesh',
    remarks: 'Dry ragi plot near electric transformer, full bill due.',
    receiptNumber: 'HB-2024-117',
    verified: false,
  },
  {
    id: 'work-5',
    farmerName: 'Chikkanna Patel',
    village: 'Besagarahalli',
    phone: '9842034567',
    crop: 'paddy',
    cropVariety: 'Paddy (Basmati)',
    fieldOwnership: 'customer',
    unit: 'acres',
    quantity: 6.0,
    rate: 3500,
    totalAmount: 21000,
    receivedAmount: 0,
    balanceAmount: 21000,
    status: 'pending',
    date: '18 Nov, 11:15 AM',
    time: '11:15 AM',
    receivedBy: 'anand',
    paymentMode: 'cash',
    driverName: 'Ramesh',
    remarks: 'Anand logged. Large basmati crop, owner in Bengaluru.',
    receiptNumber: 'HB-2024-122',
    verified: false,
  },
  {
    id: 'work-6',
    farmerName: 'Chinnasamy',
    village: 'Pongalur',
    phone: '9842045678',
    crop: 'paddy',
    cropVariety: 'Paddy (Wetland)',
    fieldOwnership: 'customer',
    unit: 'acres',
    quantity: 6.0,
    rate: 2800,
    totalAmount: 16800,
    receivedAmount: 16800,
    balanceAmount: 0,
    status: 'paid',
    date: '15 Nov 2024',
    time: '10:00 AM',
    receivedBy: 'anand',
    paymentMode: 'cash',
    driverName: 'Ramesh',
    remarks: 'Cash collected in full at tea stall.',
    receiptNumber: 'HB-2024-118',
    verified: true,
  },
  {
    id: 'work-7',
    farmerName: 'Venkatesh Rao',
    village: 'Dharapuram',
    phone: '9842056789',
    crop: 'paddy',
    cropVariety: 'Paddy (BPT-5204)',
    fieldOwnership: 'customer',
    unit: 'acres',
    quantity: 5.0,
    rate: 3000,
    totalAmount: 15000,
    receivedAmount: 8000,
    balanceAmount: 7000,
    status: 'partly_paid',
    date: '14 Nov 2024',
    time: '3:30 PM',
    receivedBy: 'boopathi',
    paymentMode: 'upi',
    driverName: 'Ramesh',
    remarks: 'Transferred 8k by PhonePe, rest due on paddy loading.',
    receiptNumber: 'HB-2024-116',
    verified: true,
  },
  {
    id: 'work-8',
    farmerName: 'Govindasamy Pillai',
    village: 'Alambadi',
    phone: '9842067890',
    crop: 'paddy',
    cropVariety: 'Paddy (Ponni)',
    fieldOwnership: 'customer',
    unit: 'acres',
    quantity: 4.0,
    rate: 3200,
    totalAmount: 12800,
    receivedAmount: 4800,
    balanceAmount: 8000,
    status: 'partly_paid',
    date: '13 Nov 2024',
    time: '11:45 AM',
    receivedBy: 'anand',
    paymentMode: 'cash',
    driverName: 'Ramesh',
    remarks: 'Token cash paid.',
    receiptNumber: 'HB-2024-115',
    verified: true,
  },
  {
    id: 'work-9',
    farmerName: 'Subramaniam',
    village: 'Kallimanthayam',
    phone: '9842078901',
    crop: 'ragi',
    cropVariety: 'Ragi (GPU-28)',
    fieldOwnership: 'customer',
    unit: 'acres',
    quantity: 3.5,
    rate: 2600,
    totalAmount: 9100,
    receivedAmount: 3100,
    balanceAmount: 6000,
    status: 'partly_paid',
    date: '12 Nov 2024',
    time: '2:15 PM',
    receivedBy: 'boopathi',
    paymentMode: 'cash',
    driverName: 'Ramesh',
    remarks: 'Balance 6,000 due this weekend.',
    receiptNumber: 'HB-2024-114',
    verified: false,
  },
  {
    id: 'work-10',
    farmerName: 'Thirumurugan',
    village: 'Oddanchatram',
    phone: '9842089012',
    crop: 'paddy',
    cropVariety: 'Paddy (CR-1009)',
    fieldOwnership: 'customer',
    unit: 'acres',
    quantity: 5.5,
    rate: 3100,
    totalAmount: 17050,
    receivedAmount: 10050,
    balanceAmount: 7000,
    status: 'partly_paid',
    date: '11 Nov 2024',
    time: '9:30 AM',
    receivedBy: 'anand',
    paymentMode: 'upi',
    driverName: 'Ramesh',
    remarks: '₹7,000 balance pending.',
    receiptNumber: 'HB-2024-113',
    verified: true,
  },
  {
    id: 'work-11',
    farmerName: 'Muthusamy',
    village: 'Mulanur',
    phone: '9842090123',
    crop: 'ragi',
    cropVariety: 'Ragi Harvest',
    fieldOwnership: 'customer',
    unit: 'hours',
    quantity: 4.0,
    rate: 2100,
    totalAmount: 8400,
    receivedAmount: 3400,
    balanceAmount: 5000,
    status: 'partly_paid',
    date: '10 Nov 2024',
    time: '4:00 PM',
    receivedBy: 'boopathi',
    paymentMode: 'cash',
    driverName: 'Ramesh',
    remarks: 'Promised by Friday.',
    receiptNumber: 'HB-2024-112',
    verified: true,
  },
  {
    id: 'work-12',
    farmerName: 'Palanisamy Gounder',
    village: 'Kundadam',
    phone: '9842001234',
    crop: 'paddy',
    cropVariety: 'Paddy Cutting',
    fieldOwnership: 'customer',
    unit: 'acres',
    quantity: 3.5,
    rate: 2800,
    totalAmount: 9800,
    receivedAmount: 4800,
    balanceAmount: 5000,
    status: 'partly_paid',
    date: '9 Nov 2024',
    time: '1:30 PM',
    receivedBy: 'anand',
    paymentMode: 'cash',
    driverName: 'Ramesh',
    remarks: 'Remaining ₹5,000 pending.',
    receiptNumber: 'HB-2024-111',
    verified: true,
  },
];

export const INITIAL_EXPENSE_ENTRIES: ExpenseEntry[] = [
  {
    id: 'exp-1',
    date: 'Today, 18 Nov 2024',
    paidBy: 'anand',
    category: 'diesel',
    amount: 4500,
    paymentMode: 'upi',
    fuelLog: {
      ratePerLitre: 93.75,
      litresFilled: 48,
      harvestAreaAcres: 16,
      litresPerAcre: 3.0,
    },
    receiptImage: FUEL_RECEIPT_IMG,
    receiptFileName: 'IOCL_Bunk_Receipt_#4192.jpg',
    remarks: 'Indian Oil bunk near Dharapuram bypass',
    machinery: 'Kubota DC-68G (KA-04-E-2194)',
    verified: true,
  },
  {
    id: 'exp-2',
    date: '17 Nov 2024',
    paidBy: 'anand',
    category: 'spares',
    amount: 14200,
    paymentMode: 'cash',
    remarks: 'Cutter bar knife section set & drive belt replacement (Kubota genuine)',
    machinery: 'Kubota DC-68G (KA-04-E-2194)',
    verified: true,
  },
  {
    id: 'exp-3',
    date: '16 Nov 2024',
    paidBy: 'boopathi',
    category: 'driver',
    amount: 12000,
    paymentMode: 'cash',
    remarks: 'Driver Ramesh weekly bata and overtime advance',
    machinery: 'Kubota DC-68G (KA-04-E-2194)',
    verified: true,
  },
  {
    id: 'exp-4',
    date: '15 Nov 2024',
    paidBy: 'anand',
    category: 'diesel',
    amount: 28500,
    paymentMode: 'hpcl_card',
    fuelLog: {
      ratePerLitre: 93.75,
      litresFilled: 304,
      harvestAreaAcres: 98,
      litresPerAcre: 3.1,
    },
    remarks: 'HPCL Fleet fuel station bulk barrel filling for week',
    machinery: 'Kubota DC-68G (KA-04-E-2194)',
    verified: true,
  },
  {
    id: 'exp-5',
    date: '14 Nov 2024',
    paidBy: 'boopathi',
    category: 'workshop',
    amount: 8500,
    paymentMode: 'cash',
    remarks: 'Thresher drum rasp bar welding and bearing greasing at Maddur workshop',
    machinery: 'Kubota DC-68G (KA-04-E-2194)',
    verified: true,
  },
  {
    id: 'exp-6',
    date: '12 Nov 2024',
    paidBy: 'boopathi',
    category: 'food',
    amount: 3200,
    paymentMode: 'cash',
    remarks: 'Field meals, drinking water cans, and night shift tea for operators',
    machinery: 'Kubota DC-68G (KA-04-E-2194)',
    verified: true,
  },
  {
    id: 'exp-7',
    date: '10 Nov 2024',
    paidBy: 'anand',
    category: 'tools',
    amount: 4800,
    paymentMode: 'cash',
    remarks: 'Heavy grease gun, spare chains, and emergency cutting torches',
    machinery: 'Kubota DC-68G (KA-04-E-2194)',
    verified: true,
  },
  {
    id: 'exp-8',
    date: '8 Nov 2024',
    paidBy: 'boopathi',
    category: 'petrol',
    amount: 1800,
    paymentMode: 'cash',
    remarks: 'Hero Splendor bike petrol for field inspection & advance collection',
    machinery: 'Hero Splendor (KA-04-R-8812)',
    verified: true,
  },
  {
    id: 'exp-9',
    date: '5 Nov 2024',
    paidBy: 'anand',
    category: 'diesel',
    amount: 32000,
    paymentMode: 'hpcl_card',
    fuelLog: {
      ratePerLitre: 93.75,
      litresFilled: 341,
      harvestAreaAcres: 110,
      litresPerAcre: 3.1,
    },
    remarks: 'Season kickoff bulk diesel purchase',
    machinery: 'Kubota DC-68G (KA-04-E-2194)',
    verified: true,
  },
  {
    id: 'exp-10',
    date: '2 Nov 2024',
    paidBy: 'anand',
    category: 'spares',
    amount: 20070,
    paymentMode: 'upi',
    remarks: 'Rubber track tensioner rollers, hydraulic oil 20L drum, filter kit',
    machinery: 'Kubota DC-68G (KA-04-E-2194)',
    verified: true,
  },
  {
    id: 'exp-11',
    date: '1 Nov 2024',
    paidBy: 'boopathi',
    category: 'driver',
    amount: 64730,
    paymentMode: 'cash',
    remarks: 'Helper wages, lorry transport advance for harvester relocation from Mandya',
    machinery: 'Kubota DC-68G (KA-04-E-2194)',
    verified: true,
  },
];

export const INITIAL_DRIVERS: DriverShift[] = [
  {
    id: 'drv-1',
    driverName: 'Ramesh (Lead Operator)',
    role: 'Primary Combine Harvester Pilot',
    phone: '9842099887',
    acresToday: 7.5,
    engineHoursToday: 6.5,
    dailyBataRate: 1500,
    acreBonusRate: 150,
    advancePaid: 12000,
    balancePayable: 4250,
    status: 'active',
  },
  {
    id: 'drv-2',
    driverName: 'Suresh (Field Helper)',
    role: 'Sack Handler & Straw Clearance',
    phone: '9842088776',
    acresToday: 7.5,
    engineHoursToday: 6.5,
    dailyBataRate: 800,
    acreBonusRate: 50,
    advancePaid: 5000,
    balancePayable: 1850,
    status: 'active',
  },
];
